sudo: false
language: python
addons:
  apt:
    packages:
    - enchant

python:
- '2.7'
install:
- pip install -q -r requirements.txt --use-mirrors

script: make html

before_install:
- echo -e "Host docs.plone.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_107e817e8752_key -iv $encrypted_107e817e8752_iv
  -in deploy_key.enc -out $HOME/.ssh/id_rsa -d

after_success:
    #- chmod 600 deploy-key
    #- mkdir -p /home/travis/.ssh
    #- chmod 700 /home/travis/.ssh
    #- mv deploy-key /home/travis/.ssh/id_rsa
- eval "$(ssh-agent)"
- chmod 600 $HOME/.ssh/id_rsa
- ssh-add $HOME/.ssh/id_rsa
- rsync -avz -e 'ssh -i /home/travis/.ssh/id_rsa' foobar2.txt docs-update@docs.plone.org:/home/docs-update
