sudo: false
language: python
addons:
  apt:
    packages:
    - enchant
python:
- '2.7'
install:
- pip install -q -r requirements.txt --use-mirrors

script: make html

before_install:
- echo -e "Host docs.plone.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_107e817e8752_key -iv $encrypted_107e817e8752_iv
  -in deploy_key.enc -out deploy_key -d

after_success:
- chmod 600 deploy-key
- mv deploy-key ~/.ssh/id_rsa
- rsync -avz -e 'ssh  -i "$HOME"/.ssh/id_rsa' foobar2.txt docs-update@docs.plone.org:/home/docs-update
