baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Plone Training - training.plone.org"
theme = "hugo-universal-theme"

[params]
	copyright = "Plone and the PloneÂ® logo are registered trademarks of the Plone Foundation."
	logo = "img/logo.png"

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Trainer"
    #subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied."

[params.features]
    enable = true
	title = "Plone Trainings"
	subtitle = "Plone training events are a great way to expand your skills. Plus it's a great way to meet the community and have fun."

[params.recent_posts]
    enable = false

[[params.menu]]
    name = "About"
	url  = "/about/"
	weight = 1

[[params.menu]]
    name = "Contact"
	url  = "/contact/"
	weight = 2
